In [1]:
import numpy as np


---

In [5]:
def array_factory(mode , shape , value = None) :
    if mode == 'zeros' :
        return np.zeros(shape)
    elif mode == 'ones' :
        return np.ones(shape)
    elif mode == 'full' :
        return np.full(shape, value)
    else :
        raise ValueError("Invalid mode. Use 'zeros', 'ones', or 'full'.")

In [8]:
print(array_factory('zeros', (2, 3)))
print("--------------")
print(array_factory('ones', (2, 3)))
print("--------------")
print(array_factory('full', (2, 3), value=7))

[[0. 0. 0.]
 [0. 0. 0.]]
--------------
[[1. 1. 1.]
 [1. 1. 1.]]
--------------
[[7 7 7]
 [7 7 7]]


---

In [2]:
def secure_reshape_and_stack(data1 , data2 , new_shape) :
    '''
    validates and converts input data to numpy arrays.
    reshapes the first dataset to a specific dimension
    vertically stacks both datasets into one matrix

    '''
    try:
        # Convert input data to numpy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)
        combined_matrix = np.vstack((reshaped_arr1, arr2))
        return combined_matrix

    except Exception as e:
        print(f"An error occurred: {e}")
        return None


In [9]:
print(secure_reshape_and_stack([[1, 2], [3, 4]], [[5, 6]], (2, 2)))
print("--------------")
print(secure_reshape_and_stack([[1, 2], [3, 4]], [[5, 6]], (4, 1)))  # This will raise an error due to incompatible shapes



[[1 2]
 [3 4]
 [5 6]]
--------------
An error occurred: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2
None
